### PR TITLE
Feature/#43 add GitHub testing action

### PR DESCRIPTION
**Pull request by Stedders**
Most basic tox run for tests added.

We should add linting as well as expanding the tox matrix, but that can be done later.

### CODE REVIEW

**Comment by synek** [comment]
I don't think we need to run `pip install -e .` or even `pip inatall -r requirements.txt`. We should only need to install `tox`. 

Also we should add caching for `tox` as well. Here's how I have done that in a previous project:

```
  unit-test:
    name: Run Unit Tests
    runs-on: ubuntu-latest
    steps:
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.9"
      - name: Checkout
        uses: actions/checkout@v2
      - name: Cache tox
        uses: actions/cache@v2
        with:
          # This path is specific to Ubuntu
          path: ./.tox/py39
          key: ${{ runner.os }}-pip-${{ hashFiles('**/poetry.lock') }}
          restore-keys: |
            ${{ runner.os }}-pip-
            ${{ runner.os }}-
      - name: Install Tox
        run: pip install tox
      - name: Tox
        run: tox
```

We will need to swap `poetry.lock` to `setup.py` (I guess?) for now, but if/when we switch to poetry we can change it back.

**Comment by Stedders** [comment]
Would be good to get your input on this @synek. I don't have much experience with GH actions/workflows.

1. Test now runs across 3.8/3.9 and Linux/Mac/Win
2. Cached tox and pip data

**Comment by synek** [comment]
I'm pretty sure we don't need to cache both pip and tox, because packages are installed in `.tox/py3.8/lib/python3.8/site-packages`.

Are we doing something with the new coverage HTML output?

**Comment by Stedders** [comment]
I added html report to check locally, my bad.

I have removed pip caching.

**Comment by synek** [comment]
Did you rebase this from master yet? I thought that those changes in `test_plan_service.py` were added in the last PR, so its strange to see them again in this PR.

Otherwise I'm happy to merge this, I'll get it in tomorrow. Great work so far, I appreciate the help!

**Comment by Stedders** [comment]
Yes, I merged that change in. Do you want me to drop it?

**Comment by synek** [comment]
I don't know if it makes a difference or not. Let's try keeping it in and see what happens

**Pull request merged**
